name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/my-portfolio

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/my-portfolio"
          docker build -t $IMAGE_URI:${{ github.run_number }} .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/my-portfolio:${{ github.run_number }}
          format: 'table'
          exit-code: '0'       # Fail the job if CRITICAL/HIGH vulns found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push image to Amazon ECR
        if: success()   # Only run if previous step (scan) passes
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/my-portfolio"
          docker push $IMAGE_URI:${{ github.run_number }}
  deploy-ec2:
    runs-on: ubuntu-latest
    needs: build   # Wait for build job to finish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1️⃣ Deploy image to EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}          # Public IP or DNS of your EC2
          username: ${{ secrets.EC2_USER }}      # Usually "ec2-user" or "ubuntu"
          key: ${{ secrets.EC2_SSH_KEY }}        # Private key (stored in GitHub Secrets)
          port: 22
          script: |
            IMAGE_URI=${{needs.build.outputs.IMAGE_URI }}
            IMAGE_TAG=${{ github.run_number }}

            # Login to ECR on EC2
            aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin $IMAGE_URI

            # Pull the latest image
            docker pull $IMAGE_URI:$IMAGE_TAG

            # Stop previous container (if any)
            docker rm -f my-portfolio || true

            # Run new container
            docker run -d --name my-portfolio -p 80:80 $IMAGE_URI:$IMAGE_TAG

            # Verify container is running
            docker ps

